import pandas as pd
import sqlite3

df = pd.read_csv('refinal_merged_df.csv', encoding='utf-8')

database = 'db.sqlite3'
conn = sqlite3.connect(database)
dtype = {
    'Unnamed':'IntegerField',
    '이름': 'CharField',
    '이메일': 'EmailField',
    '견종': 'CharField',
    '견종_코드': 'CharField',
    '크기': 'CharField',
    '크기_코드': 'CharField',
    '색상': 'CharField',
    '색상_코드': 'CharField',
    '연령대': 'CharField',
    '연령대_코드': 'CharField',
    '상태': 'CharField',
    '상태_코드': 'CharField',
    '브랜드': 'CharField',
    '브랜드_코드': 'CharField',
    '사료': 'CharField',
    '사료_코드': 'CharField',
    '평점': 'FloatField',
    '후기': 'TextField',
    '주소': 'CharField',
    '국가': 'CharField',
    '시도': 'CharField',
    '시군구': 'CharField',
    'CP': 'IntegerField',
    'CF': 'IntegerField',
    'CR': 'IntegerField',
    'CB': 'IntegerField',
    'CA': 'IntegerField',
    'PO': 'IntegerField',
    'WA': 'IntegerField',
    'field_8':'CharField',
    'field_9':'CharField',
    'field_10':'CharField',
    'field_11':'CharField',
    'field_12':'CharField',
    'field_13':'CharField',
    'field_14':'CharField',
    'field_15':'CharField',
    'field_16':'CharField',
    'field_17':'CharField',
    'field_18':'CharField',
    'field_19':'CharField',
    'field_20':'CharField',
    'field_21':'CharField',
    'field_22':'CharField',
    'field_23':'CharField',
    'field_24':'CharField',
    'field_25':'CharField',
    'field_26':'CharField',
    'field_27':'CharField',
    'field_28':'CharField',
    'field_29':'CharField',
    'field_30':'CharField',
    'field_31':'CharField',
    'field_32':'CharField',
    'field_33':'CharField',
    'field_34':'CharField',
    'field_35':'CharField',
    'field_36':'CharField',
    'field_37':'CharField',
    'field_38':'CharField',
    'field_39':'CharField',
    'field_40':'CharField',
    'field_41':'CharField',
    'field_42':'CharField',
    'field_43':'CharField',
    'field_44':'CharField',
    'field_45':'CharField',
    'field_46':'CharField',
    'field_47':'CharField',
    'field_48':'CharField',
    'field_49':'CharField',
    'field_50':'CharField',
    'field_51':'CharField',
    'field_52':'CharField',
    'field_53':'CharField',
    'field_54':'CharField',
    'field_55':'CharField',
    'field_56':'CharField',
    'field_57':'CharField',
    'field_58':'CharField',
    'field_59':'CharField',
    'field_60':'CharField',
    'field_61':'CharField',
    'field_62':'CharField',
    'field_63':'CharField',
    'field_64':'CharField',
    'field_65':'CharField',
    'field_66':'CharField',
    'field_67':'CharField',
    'field_68':'CharField',
    'field_69':'CharField',
    'field_70':'CharField',
    'field_71':'CharField',
    'field_72':'CharField',
    'field_73':'CharField',
    'field_74':'CharField',
    'field_75':'CharField',
    'field_76':'CharField',
    'field_77':'CharField',
    'field_78':'CharField',
    'field_79':'CharField',
    'field_80':'CharField',
    'field_81':'CharField',
    'field_82':'CharField',
    'field_83':'CharField',
}
df.to_sql(name='dog_info', con=conn, if_exists='replace',
          dtype=dtype, index=True, index_label='id')
conn.close()