# Generated by Django 4.2.5 on 2023-11-07 08:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('cp', models.IntegerField()),
                ('cf', models.IntegerField()),
                ('cr', models.IntegerField()),
                ('cb', models.IntegerField()),
                ('ca', models.IntegerField()),
                ('po', models.IntegerField()),
                ('wa', models.IntegerField()),
            ],
            options={
                'db_table': 'my_product',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('content', models.TextField()),
                ('create_dt', models.DateTimeField()),
                ('updata_dt', models.DateTimeField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'db_table': 'my_review',
            },
        ),
    ]
