# Generated by Django 4.2.5 on 2023-11-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='updata_dt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
