# Generated by Django 4.2.5 on 2023-11-07 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Age',
            fields=[
                ('age_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'my_dog_age',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('color_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'my_dog_color',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('size_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'my_dog_size',
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('species_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'my_dog_species',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('state_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'my_dog_state',
            },
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('dog_id', models.AutoField(primary_key=True, serialize=False)),
                ('age_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dog.age')),
                ('color_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dog.color')),
                ('size_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dog.size')),
                ('species_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dog.species')),
                ('state_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dog.state')),
            ],
            options={
                'db_table': 'my_dog',
            },
        ),
    ]
