# Generated by Django 4.2.5 on 2023-11-06 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dogsurvey',
            options={},
        ),
    ]
