# Generated by Django 4.2.5 on 2023-11-07 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('create_dt', models.DateTimeField()),
                ('update_dt', models.DateTimeField()),
            ],
            options={
                'db_table': 'my_order',
            },
        ),
        migrations.CreateModel(
            name='Order_Detail',
            fields=[
                ('order_detial_id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.IntegerField()),
                ('count', models.IntegerField()),
                ('pay', models.CharField(choices=[('a', '계좌이체'), ('b', '무통장 입금'), ('c', '카드')], max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
            options={
                'db_table': 'my_order_detail',
            },
        ),
    ]
